echo Running tester $1 against server $2 ...
echo Building tester and server images ...
docker build -t $1 testers/$1
docker build -t $2 servers/$2

echo Starting server ...
docker run -d --name=server --rm --network=testnet $2
if [[ "$2" == nextcloud-server ]]
  then
    echo Waiting for Nextcloud server to start ...
    sleep 10
    docker logs server
    echo Running init script for Nextcloud server ...
    docker exec -u www-data -it server sh /init.sh
fi

echo Running $1 tester interactively ...
docker run --name tester --rm --env-file servers/$2/env.list --network=testnet -it $1 /bin/bash

echo Tester exited, stopping server ...
docker stop server
