echo Testing $1...
echo Building image...
docker build -t $1 servers/$1

echo Starting server...
docker run -d --name=server --rm --network=testnet $1
if [[ "$1" == nextcloud-server ]]
  then
    echo Waiting for Nextcloud server to start ...
    sleep 10
    docker logs server
    echo Running init script for Nextcloud server ...
    docker exec -u www-data -it server sh /init.sh
    docker exec -u root -it server service apache2 reload
fi

echo Running webid-provider tester...
docker run  --cap-add=SYS_ADMIN --network=testnet --env-file servers/$1/env.list webid-provider 2> reports/$1-webid-provider.txt

echo Running solid-crud tester...
docker run --network=testnet --env-file servers/$1/env.list solid-crud 2> reports/$1-solid-crud.txt

echo Running open-cloud-mesh tester...
docker run --network=testnet --env-file servers/$1/env.list open-cloud-mesh 2> reports/$1-open-cloud-mesh.txt

echo Stopping server...
docker stop server
